name: development deployment

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [dev]
  # pull_request:
  #   branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.push == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [16.x]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Setting .env
        run: |
          echo "REACT_APP_AUTH_GITHUB_URL=${{ secrets.AUTH_GITHUB_URL }}" >> .env
          echo "REACT_APP_AUTH_GOOGLE_URL=${{ secrets.AUTH_GOOGLE_URL }}" >> .env
          echo "REACT_APP_AUTH_KAKAO_URL=${{ secrets.AUTH_KAKAO_URL }}" >> .env
          echo "REACT_APP_API_URL=${{ secrets.API_URL }}" >> .env
          cat .env
      - name: Build
        run: yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync build/ s3://${{ secrets.DEV_AWS_S3_BUCKET }} --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DEV_AWS_DISTRIBUTION_ID}} --paths "/*"
